### ISSUE TITLE
Just a small edit

### ISSUE THREAD

**Issue by hidara2000** [quotetherevan/slowDownFeatures#3]
Cheers for this script. I've just noticed that the following lines need to be updated to match S3D current tagging format. Cheers again

12: outerPerimRE = re.compile( r";\sfeature\souter\sperimeter" )
13: denseSupportRE = re.compile( r";\sfeature\sdense\ssupport" )

**Comment by quotetherevan** [comment]
thanks for the fix! integrated in https://github.com/quotetherevan/slowDownFeatures/commit/617c95ae79a2e52b0c6988ad3618ba6a640725ea
